resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.0/deploy/static/provider/cloud/deploy.yaml

patches:
  - path: service-nodeport.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
  - path: patch-nodeselector.yaml
    target:
      kind: Deployment
      name: ingress-nginx-controller
