apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc
  namespace: jenkins
data:
  jcasc.yaml: |
    jenkins:
      systemMessage: "CI/CD Pipeline for DevOps Diploma Project"
      numExecutors: 2
      remotingSecurity:
        enabled: true
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: admin
              password: ${JENKINS_ADMIN_PASSWORD}
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false

      clouds:
        - kubernetes:
            name: "kubernetes"
            namespace: jenkins
            serverUrl: "https://kubernetes.default"
            skipTlsVerify: true
            jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080/"
            jenkinsTunnel: "jenkins.jenkins.svc.cluster.local:50000"
            webSocket: false
            templates:
              - name: "kubectl-agent"
                serviceAccount: "jenkins-sa"
                label: "kubectl"
                containers:
                  - name: kubectl
                    image: AGENT_IMAGE 
                    command: "cat"
                    ttyEnabled: true

    tool:
      jdk:
        installations:
          - name: "jdk17"
            home: "/opt/java/openjdk"
            properties: []

    unclassified:
      location:
        url: http://jenkins.local
        adminAddress: ${ADMIN_ADDRESS} 

    appearance:
      locale:
        systemLocale: en
        ignoreAcceptLanguage: true
        allowUserPreferences: false

    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  id: github-credentials
                  scope: GLOBAL
                  username: ${GITHUB_USERNAME}
                  password: ${GITHUB_TOKEN}
              - usernamePassword:
                  id: dockerhub-cred
                  scope: GLOBAL
                  username: ${DOCKERHUB_USERNAME}
                  password: ${DOCKERHUB_TOKEN}
              - string:
                  id: telegram-token
                  scope: GLOBAL
                  secret: ${TELEGRAM_TOKEN}
              - string:
                  id: github-webhook-secret
                  scope: GLOBAL
                  secret: ${GITHUB_WEBHOOK_SECRET}

    jobs:
      - script: >
          multibranchPipelineJob('Diplom_DOS25') {
            branchSources {
              github {
                id('61887015')
                repoOwner('kirillank')
                repository('Diplom_DOS25')
                scanCredentialsId('github-credentials')
              }
              configure { node ->
                def traits = node / 'source' / 'traits'
                traits.appendNode('jenkins.scm.impl.trait.BranchDiscoveryTrait', '')
                traits.appendNode('org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait') {
                  strategyId '1'
                }
                traits.appendNode('jenkins.scm.impl.trait.ScmSourceSuppressAutomaticTriggeringTrait', '')
              }
            }
            factory {
              workflowBranchProjectFactory {
                scriptPath('Jenkinsfile')
              }
            }
            configure { project ->
              project / triggers / 'com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger' {
                spec('')
              }
            }
          }

