namespace: jenkins
resources:
  - namespace.yaml
  - serviceaccount.yaml 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - jenkins-pvc.yaml
  - jenkins-pv.yaml
  - configmap.yaml

secretGenerator:
  - name: jenkins-secrets
    envs:
      - secrets.env
generatorOptions:
  disableNameSuffixHash: true      

