namespace: jenkins
resources:
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- jenkins-pvc.yaml
- jenkins-pv.yaml
- configmap.yaml
- clusterrolebinding.yaml
- sealedsecret.yaml


generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
