namespace: jenkins
resources:
  - namespace.yaml
  - serviceaccount.yaml 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - jenkins-pvc.yaml
  - jenkins-pv.yaml
  - configmap.yaml
  - role.yaml
  - rolebinding.yaml


secretGenerator:
  - name: jenkins-secrets
    envs:
      - secrets.env

  - name: dockerhub-cred               
    files:
      - config.json=config.json 
    type: Opaque  
generatorOptions:
  disableNameSuffixHash: true      

