apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins
resources:
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- jenkins-pvc.yaml
- jenkins-pv.yaml
- configmap.yaml
- clusterrolebinding.yaml
- sealedsecret.yaml


generatorOptions:
  disableNameSuffixHash: true

images:
  - name: AGENT_IMAGE
    newName: kirillank04/kubectl-kustomize-helm
    newTag: latest

  - name: JENKINS_IMAGE
    newName: kirillank04/jenkins
    newTag: dos25-onl

  - name: WEBHOOK_IMAGE
    newName: webhookrelay/webhookrelayd
    newTag: latest



