namespace: jenkins
resources:
  - namespace.yaml
  - serviceaccount.yaml 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - jenkins-pvc.yaml
  - jenkins-pv.yaml
  - configmap.yaml

secretGenerator:
  - name: jenkins-secrets
    envs:
      - secrets.env

  - name: dockerhub-cred               
    files:
      - .dockerconfigjson=config.json
    type: kubernetes.io/dockerconfigjson

generatorOptions:
  disableNameSuffixHash: true      

