apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-secret-reader
  namespace: jenkins
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create"]
