apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: jenkins
type: Opaque
stringData:            
  JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
  GITHUB_USERNAME:        ${GITHUB_USERNAME}
  GITHUB_TOKEN:           ${GITHUB_TOKEN}
  TELEGRAM_TOKEN:         ${TELEGRAM_TOKEN}

