apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels: { app: my-app }
  template:
    metadata: { labels: { app: my-app } }
    spec:
      nodeSelector: { kubernetes.io/hostname: k8s-app }
      containers:
        - name: my-app
          image: kirillank04/my-app:latest 
          ports: [ { containerPort: 8080 } ]

