- name: Disable swap
  command: swapoff -a

- name: Comment out swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*swap)'
    replace: '#\1'

- name: Enable bridge network sysctl
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Set sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl params
  command: sysctl --system
