apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch 
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage


