- name: Download MetalLB native manifest
  ansible.builtin.get_url:
    url: "{{ metallb_core_url }}"
    dest: "{{ tmp_dir }}/metallb-native.yaml"
    mode: "0644"

- name: Apply MetalLB core (CRDs + controller/speaker)
  kubernetes.core.k8s:
    state: present
    src: "{{ tmp_dir }}/metallb-native.yaml"

- name: Wait for MetalLB CRDs to be registered
  kubernetes.core.k8s_info:
    api_version: metallb.io/v1beta1
    kind: IPAddressPool
  register: crd_check
  retries: 12
  delay: 10
  until: crd_check.resources is not none

- name: Apply MetalLB IPAddressPool + L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', metallb_config_dir ~ '/ip-pool.yaml') }}"

