apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - rbac.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus.yml
    options:
      disableNameSuffixHash: true
  - name: prometheus-rules
    files:
      - rules/deployment-events.yml
      - rules/node-exporter-rules.yml
    options:
      disableNameSuffixHash: true
