apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    templates:
      - /etc/alertmanager/templates/telegram.tmpl

    route:
      receiver: telegram
      group_by: ['alertname','job','instance']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

    receivers:
      - name: telegram
        telegram_configs:
          - bot_token: ${TELEGRAM_TOKEN}
            chat_id: ${CHAT_ID}
            parse_mode: MarkdownV2
            send_resolved: true
            message: '{{ template "telegram.default" . }}'
