apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

configMapGenerator:
  - name: alertmanager-templates
    files:
      - telegram.tmpl
    options:
      disableNameSuffixHash: true


