groups:
- name: app-availability.rules
  rules:
  - alert: AppAvailable
    expr: changes(up{job="spring-petclinic"}[5m]) > 0
    for: 0m
    labels:
      severity: info
    annotations:
      summary: "Application is now available"
      description: "Endpoint /actuator/prometheus is up; first successful scrape detected."
